### ISSUE TITLE
IndexOutOfRangeException

### ISSUE THREAD

**Issue by Skosn** [visualdesigncafe/nature-renderer#10]
**Describe the bug**
You probably have to implement a null check in ClearEmptyCells from NatureInstanceStreamer.

Full Stacktrace:

IndexOutOfRangeException: Index was outside the bounds of the array.
VisualDesignCafe.Rendering.Nature.NatureInstanceStreamer.ClearEmptyCells () (at C:/Visual Design Cafe/Projects/Nature Renderer/Unity/Nature Renderer 2022/Assets/Visual Design Cafe/Nature Renderer/Plugins/Runtime/VisualDesignCafe.Rendering.Nature/NatureInstanceStreamer.cs:288)
VisualDesignCafe.Rendering.Nature.NatureInstanceStreamer.GetBuffersForCellsInRange (UnityEngine.Camera camera, System.Int32 frameId, System.Double range, VisualDesignCafe.Rendering.Instancing.CullingSettings cullingSettings, System.Collections.Generic.List`1[T] buffers) (at C:/Visual Design Cafe/Projects/Nature Renderer/Unity/Nature Renderer 2022/Assets/Visual Design Cafe/Nature Renderer/Plugins/Runtime/VisualDesignCafe.Rendering.Nature/NatureInstanceStreamer.cs:212)
VisualDesignCafe.Rendering.Instancing.CameraRenderer.RenderObject (VisualDesignCafe.Rendering.Instancing.CameraRenderer+ObjectRenderData obj, VisualDesignCafe.Rendering.Instancing.SceneRenderSettings& sceneSettings) (at C:/Visual Design Cafe/Projects/Nature Renderer/Unity/Nature Renderer 2022/Assets/Visual Design Cafe/Nature Renderer/Plugins/Runtime/VisualDesignCafe.Rendering.Instancing/CameraRenderer.cs:340)
VisualDesignCafe.Rendering.Instancing.CameraRenderer.Render () (at C:/Visual Design Cafe/Projects/Nature Renderer/Unity/Nature Renderer 2022/Assets/Visual Design Cafe/Nature Renderer/Plugins/Runtime/VisualDesignCafe.Rendering.Instancing/CameraRenderer.cs:263)
VisualDesignCafe.Rendering.Instancing.FrameRenderer.OnBeginContextRendering (UnityEngine.Rendering.ScriptableRenderContext context, System.Collections.Generic.List`1[T] cameras) (at C:/Visual Design Cafe/Projects/Nature Renderer/Unity/Nature Renderer 2022/Assets/Visual Design Cafe/Nature Renderer/Plugins/Runtime/VisualDesignCafe.Rendering.Instancing/FrameRenderer.cs:36)
UnityEngine.Debug:LogException(Exception)
VisualDesignCafe.Rendering.Instancing.FrameRenderer:OnBeginContextRendering(ScriptableRenderContext, List`1) (at C:/Visual Design Cafe/Projects/Nature Renderer/Unity/Nature Renderer 2022/Assets/Visual Design Cafe/Nature Renderer/Plugins/Runtime/VisualDesignCafe.Rendering.Instancing/FrameRenderer.cs:40)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

**Expected behavior**
No Exception.

**Project(please complete the following information):**
 - Unity version: 2202.3.19f
 - Render Pipeline: HDRP
 - Render Pipeline Version 14.0.10
 - Nature Renderer Version 2022

**Comment by maxplooi** [comment]
Thank you for reporting this. Is there any specific action or steps to reproduce this error? I am looking into it but I can't seem to reproduce it. 

I have just published version **2022.0.3** which contains a small improvement to this code which might solve the issue. Could you download it and give it a try? You can update by going to **Help > Nature Renderer > Check for Updates** in the Unity editor.

**Comment by Skosn** [comment]
Hello,

seems to be fixed with the update, thanks.
