### ISSUE TITLE
Crashes Build of game

### ISSUE THREAD

**Issue by retlaws** [visualdesigncafe/nature-renderer#27]
**BUG DESCRIPTION**

If I do a build of the game it crashes when I try and load the level in. After a lot of trial and error I narrowed it down to Nature Renderer. If I remove any vegetation from Nature Renderer but still leave Nature Renderer attached to the terrain it will load ok. There is a dump file created when it crashes which states: _The thread tried to read from or write to a virtual address for which it does not have the appropriate access._

So I guess the issue is something to do with Nature Renderer trying to load the vegetation but having an access issue but beyond that I am stumped. 

**To Reproduce**
1. Build game
2. Load game
3. Game crashes

**Expected behavior**

For it not to crash

**Project(please complete the following information):**
 - Unity version: 2022.3.15f1
 - Render Pipeline: Built in render pipeline
 - Render Pipeline Version: Not sure where I find this, Googling this hasn't given a way to find this information
 - Nature Renderer Version 2022.0.3

**System (please complete the following information):**
 - Platform: Windows
 - Platform OS: Windows 10 (version 10.0.19045)
 - Graphics API and Version: I assume Direct X11 

**Additional context**

**Comment by retlaws** [comment]
Am I going to get a response to this? I broke my laptop, finally sorted a replacement and come back and still no response.

**Comment by rendrop** [comment]
I am having the same issue.

Crashes on player build right after Nature Renderer initialization with "The thread tried to read from or write to a virtual address for which it does not have the appropriate access." message.

I'm on 2022.3.38f1, HDRP 14 with NR 2022.0.4.

Platform is Windows 11 23H2 and both DX11 and DX12 crashed on player build.

Project is working fine on Editor.

**Comment by stonstad** [comment]
Did you guys get this fixed?  If not, I hope you posted an appropriate review?

**Comment by rendrop** [comment]
> Did you guys get this fixed? If not, I hope you posted an appropriate review?

Are you using IL2CPP as scripting backend and (perhaps) are using other precompiled dll plugins? 

If yes, I found that switching to Mono fix this problem for me.

**Comment by retlaws** [comment]
I did get this fixed but can't remember what the issue was - it was a long time ago. I thought I closed this already. Will close it now.
