### ISSUE TITLE
Error Occurred After Building Addressables

### ISSUE THREAD

**Issue by Robyiicorporate** [visualdesigncafe/nature-renderer#58]
**Describe the bug**
An error occurred after building the addressables in Unity while using Nature Renderer. Despite following the standard procedures, I am facing an issue with shader errors related to the maximum sampler register index being exceeded.

Error Messages:

Shader error in 'NatureManufacture/URP/Foliage/Bark (Nature Renderer)': maximum ps_5_0 sampler register index (16) exceeded at line 382 (on d3d11).
Shader error in 'NatureManufacture Shaders/Water/Water River Offset Vertex Color Flow': maximum ps_5_0 sampler register index (16) exceeded at line 538 (on d3d11) (repeated error).

**To Reproduce**
1.Open Unity Editor and load the project.
2.Navigate to the addressables configuration and initiate a build.
3.Observe the shader compilation process.
4.Errors appear in the console related to specific shaders.

**Expected behavior**
Expected the shaders to compile without errors and for the addressables build to complete successfully without exceeding the hardware limits for shader sampler registers.

**Screenshots**
![Screenshot 2024-06-27 132132](https://github.com/visualdesigncafe/nature-renderer/assets/161794075/032a3671-bb0a-46ee-9796-58e494398e9e)
![Screenshot 2024-06-27 132359](https://github.com/visualdesigncafe/nature-renderer/assets/161794075/2d6b9816-9c45-4fb7-a0a7-8ae5ec92d938)

**Project(please complete the following information):**
 - Unity Version: Unity 2021.3.20f1
 - Nature Renderer Version: Nature renderer 2021.2.0
 - Render Pipeline: Universal Render Pipeline
 - Render Pipeline Version 12.0.10

**System (please complete the following information):**
 - Platform:  Windows
 - Platform OS: Windows 11
 - Graphics API and Version DirectX11

**Comment by maxplooi** [comment]
This is an issue of Nature Manufacture's shaders, not Nature Renderer. I recommend contacting them to solve this issue.
