### ISSUE TITLE
Growing / Shrinking of terrain details (NR 2021

### ISSUE THREAD

**Issue by westonleavitt** [visualdesigncafe/nature-renderer#62]
There seems to be no uniformity to objects growing/shrinking based on camera distance. For example here are two rocks from the same detail group, one shrinks, one does not. 

Is it possible to just turn the shrinking off completely? I have scoured the docs on this. It is not a shader thing

This video shows the issue: https://streamable.com/6dkyjh

**Comment by maxplooi** [comment]
This is the **Density in Distance** setting in action. The density of objects is automatically reduced in the distance by automatically scaling down and eventually culling some objects (based on a noise pattern). This can drastically improve performance for transparent objects by reducing [overdraw](https://visualdesigncafe.com/nature-renderer/docs/2020/overdraw). You can tweak the setting in the [Object Settings](https://visualdesigncafe.com/nature-renderer/docs/2022/object-settings), [Camera Settings](https://visualdesigncafe.com/nature-renderer/docs/2022/camera-settings), or [Default Settings](https://visualdesigncafe.com/nature-renderer/docs/2022/default-settings) to change the distance, density, or disable it completely.

**Comment by westonleavitt** [comment]
Thanks
