### ISSUE TITLE
Ambient Lighting on Meshes/Textures

### ISSUE THREAD

**Issue by NicholasBrown-01** [visualdesigncafe/nature-renderer#7]
**Describe the bug**
Cannot increase the distance in which vegetation that has been converted will render light/ambient light that affects it. I have included a screenshot of being a certain distance from an object, followed by the next screen shot of moving closer a few paces. If I deactivate the Nature Renderer Script attached to the terrain, the problem goes away and all vegetation meshes/textures render ambient lighting correctly. Any help is appreciated thank you!

**Screenshots**

![1](https://github.com/visualdesigncafe/nature-renderer/assets/119603466/bf42affb-ac8c-4217-b5d8-daa9647ced05)
![2](https://github.com/visualdesigncafe/nature-renderer/assets/119603466/de3f96e3-63d6-4d81-9a9f-dc1e081446c1)

**Project(please complete the following information):**
 - Unity version: 2022.3.1f1
 - Render Pipeline: Universal Render Pipeline
 - Nature Renderer Version 2022.0.0 October 12, 2023

**System (please complete the following information):**
 - Platform: Windows
 - Graphics API and Version: DirectX11

**Comment by maxplooi** [comment]
Thank you for reporting this. Could you let me know the URP settings that you are using? I looked into it and the most likely reason for light not rendering is the _"Per Object Limit"_ for _"Additional Lights"_ in the URP settings when using Forward rendering. It seems that Unity counts all of the vegetation as one object when using GPU Instancing, so with a lot of lights in the scene it can quickly reach the limit. 
![unity-urp-settings-per-object-limit-for-additional-lights](https://github.com/visualdesigncafe/nature-renderer/assets/9071464/9768f07f-017f-4783-93fc-358b701dcddd)

The best solution for this would be to use **Forward+** rendering. You can change this in the URP Renderer settings:
![unity-urp-forward-plus-rendering](https://github.com/visualdesigncafe/nature-renderer/assets/9071464/7a9b90a7-189f-46ab-9fbe-f49ee66ea0f2)

I could not find any other reason why light would not render. If changing the above settings does not solve the issue then please let me know and I'll look into it further.

**Comment by NicholasBrown-01** [comment]
That solved it. I wasn't even considering the amount of lights. Thank you. Will update my review as stated. Thanks again.
