### ISSUE TITLE
Undo crashes Unity

### ISSUE THREAD

**Issue by Ghostdreamer11** [visualdesigncafe/nature-renderer#9]
**Describe the bug**
Ctrl+Z after "Convert to Nature Instance" crashes unity

**To Reproduce**
1. Create a prefab of something, drag into scene
2. Right click > Convert to Nature Instance
3. Ctrl+Z
4. Crash

**Expected behavior**
Preferably, undo happens. Alternatively, a debug.error says you cant undo. Anything other than a hard crash

**Screenshots**

**Project(please complete the following information):**
 - Unity version: 2022.3.7f1
 - Render Pipeline: URP
 - Render Pipeline Version 14.0
 - Nature Renderer Version: 2022.0.2

**System (please complete the following information):**
 - Platform: Windows
 - Platform OS: 11
 - Graphics API and Version DX12

**Additional context**

**Comment by maxplooi** [comment]
Thank you for reporting this issue. I can confirm that Ctrl+Z causes a crash. It seems there has been a change in how Unity handles Undo operations resulting in this crash in recent versions of Unity. I have found a workaround and have included a fix for the next update.

**Comment by maxplooi** [comment]
Version **2022.0.3** is now available and contains a fix for this crash. You can go to **Help > Nature Renderer > Check for Updates** in the Unity editor to download the update.
